[package]
name = "voting_contract"
type = "contract"
authors = ["Satyam Bansal <satyamsgsits1994@gmail.com>"]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.2", directory = "noir-projects/aztec-nr/aztec" }
